// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proto/model/data.proto

// package 명은 go package 에 지정된 경로의 제일 마지막 것으로 해야 한다.

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg    string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Number int32  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *MyData) Reset() {
	*x = MyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyData) ProtoMessage() {}

func (x *MyData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyData.ProtoReflect.Descriptor instead.
func (*MyData) Descriptor() ([]byte, []int) {
	return file_proto_model_data_proto_rawDescGZIP(), []int{0}
}

func (x *MyData) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MyData) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_proto_model_data_proto protoreflect.FileDescriptor

var file_proto_model_data_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x32, 0x0a, 0x06, 0x4d, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_model_data_proto_rawDescOnce sync.Once
	file_proto_model_data_proto_rawDescData = file_proto_model_data_proto_rawDesc
)

func file_proto_model_data_proto_rawDescGZIP() []byte {
	file_proto_model_data_proto_rawDescOnce.Do(func() {
		file_proto_model_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_data_proto_rawDescData)
	})
	return file_proto_model_data_proto_rawDescData
}

var file_proto_model_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_model_data_proto_goTypes = []interface{}{
	(*MyData)(nil), // 0: proto.model.MyData
}
var file_proto_model_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_model_data_proto_init() }
func file_proto_model_data_proto_init() {
	if File_proto_model_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_model_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_data_proto_goTypes,
		DependencyIndexes: file_proto_model_data_proto_depIdxs,
		MessageInfos:      file_proto_model_data_proto_msgTypes,
	}.Build()
	File_proto_model_data_proto = out.File
	file_proto_model_data_proto_rawDesc = nil
	file_proto_model_data_proto_goTypes = nil
	file_proto_model_data_proto_depIdxs = nil
}
